imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: retromat_plan_titles.yml }
    - { resource: retromat_sources.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enabled: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    assets: ~
    cache:
        app: cache.adapter.redis
        default_redis_provider: "redis://%redis_connection%"
        prefix_seed: "retromat"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        unix_socket: "%database_socket%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                query_cache_driver:
                    type:                 array
                    host:                 ~
                    port:                 ~
                    database:             ~
                    instance_class:       ~
                    class:                ~
                    id:                   ~
                    namespace:            null
                    cache_provider:       null
                metadata_cache_driver:
                    type:                 redis
                    host:                 /Users/timon/.redis/sock
                    port:                 ~
                    database:             ~
                    instance_class:       ~
                    class:                ~
                    id:                   ~
                    namespace:            null
                    cache_provider:       null
                result_cache_driver:
                    type:                 array
                    host:                 ~
                    port:                 ~
                    database:             ~
                    instance_class:       ~
                    class:                ~
                    id:                   ~
                    namespace:            null
                    cache_provider:       null

doctrine_migrations:
    dir_name: "%kernel.project_dir%/app/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }

presta_sitemap:
    timetolive: 3600

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%retromat_backend_mail%"
        sender_name: "%retromat_backend_mail%"
    registration:
        confirmation:
            enabled: true

fos_rest:
    routing_loader:
        default_format: json
    format_listener: true
    view:
        view_response_listener: 'force'
    body_listener: true
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # added for the presta sitemap, but used by others as well: http://symfony.com/doc/current/console/request_context.html
    router.request_context.host:   plans-for-retrospectives.com
    router.request_context.scheme: https
