language: php

php:
    - 7.0
    - 7.1

before_install:
    - cp backend/app/config/parameters.yml.travis backend/app/config/parameters.yml

install:
    - composer install --working-dir=backend

before_script:
    - php backend/bin/console doctrine:database:create
    - php backend/bin/console doctrine:migrations:migrate --no-interaction
    - php backend/bin/console retromat:import:activities
    - backend/bin/travis-ci/generate-templates-from-retromat-v1.sh

script:
    - backend/vendor/bin/simple-phpunit -c backend

notifications:
    on_success: always
    on_failure: always
    email:
        recipients:
            - timon.fiddike@agile.coach
