# No translation properties need to be serialized as such, because
# using the serializer config + the magic __get method in Activity2
# name, summary and desc are included in serializing
# the respective Activity2 itself.

#AppBundle\Entity\Activity2Translation:
#    attributes:
#        name:       { groups: ['rest'] }
#        summary:    { groups: ['rest'] }
#        desc:       { groups: ['rest'] }